# Generated by Django 3.0.4 on 2020-03-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouploop', '0002_auto_20200306_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='circle',
            name='title',
            field=models.TextField(),
        ),
    ]
