# Generated by Django 3.0.4 on 2020-03-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grouploop', '0003_auto_20200309_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
